Repository gigascience/gigadb-website, pull requests merged in 2022-01, with the labels that each got.

#897 849 samples admin crash fix
  .gitlab-ci.yml
  protected/components/FormattedDatasetSamples.php
  protected/models/Sample.php
  protected/views/adminDatasetSample/admin.php
  protected/views/adminSample/admin.php
  tests/acceptance/AdminDatasetSample.feature
  tests/acceptance/AdminSample.feature
  tests/unit.suite.yml
  tests/unit/SampleTest.php
  tests/unit/bootstrap.php
  tests/unit_runner
Labels: task:Size=6h

#912 Dataset page files table pagination and performance issues
  .gitlab-ci.yml
  composer.lock
  ops/configuration/nginx-conf/nginx.conf
  ops/configuration/nginx-conf/sites/CI/gigadb.CI.http.conf
  ops/configuration/nginx-conf/sites/dev/gigadb.dev.http.conf
  ops/configuration/nginx-conf/sites/nginx.target_deployment.https.conf.dist
  ops/configuration/php-conf/php-7.2-production.ini
  ops/configuration/variables/env-sample
  ops/deployment/docker-compose.build.yml
  ops/deployment/docker-compose.yml
  ops/packaging/Dockerfile
  ops/packaging/Production-Dockerfile
  protected/components/StoredDatasetFiles.php
  protected/components/WebUser.php
  protected/views/dataset/view.php
  tests/_support/WebsiteUserSteps.php
  tests/acceptance.suite.yml
  tests/acceptance/DatasetView.feature
  tests/unit_runner
Labels: task:Size=14h

#885 Remove extra hyphen mark between the semantic icons
  ops/configuration/yii-conf/main.php.dist
  protected/components/FormattedDatasetMainSection.php
  protected/tests/unit/FormattedDatasetMainSectionTest.php
  protected/tests/unit/StoredDatasetMainSectionTest.php
  protected/views/dataset/view.php
  tests/_support/AcceptanceTester.php
  tests/acceptance.suite.yml
  tests/acceptance/DatasetView.feature
Labels: task:Size=2h

#899 Fix update password error
  ops/pipelines/gigadb-deploy-jobs.yml
  protected/migrations/fix_import/m500000_000100_update_password_column_gigadb_user_tab.php
  tests/acceptance/ChangePassword.feature
Labels: task:Size=4h

#909 Server error occurs when updating file as an admin with no set release date
  protected/models/File.php
  tests/acceptance.suite.yml
  tests/acceptance/AdminFileForm.feature
  tests/acceptance/initdb.php
  tests/acceptance_runner
Labels: task:Size=1h
