Repository gigascience/gigadb-website, pull requests merged in 2025-07, with the labels that each got.

#2407 Upgrade eol buster to bullseye
  CHANGELOG.md
  fuw/app/console/Worker-Dockerfile
  fuw/docker-pure-ftpd/Dockerfile
  ops/deployment/docker-compose.yml
  ops/packaging/VueDev-Dockerfile
  ops/packaging/Worker-Dockerfile
Labels: Rija, pr:simple

#2227 Create meta tags based on envs
  CHANGELOG.md
  features/pages-not-indexed-by-search-engines.feature
  ops/configuration/yii-conf/index.dev.php.dist
  ops/configuration/yii-conf/index.live.php.dist
  ops/configuration/yii-conf/index.staging.php.dist
  ops/pipelines/gigadb-test-jobs.yml
  protected/components/Controller.php
  protected/controllers/DatasetController.php
  protected/views/dataset/_meta_tags.php
  protected/views/layouts/main.php
  tests/_support/AcceptanceTester.php
  tests/acceptance/DatasetMetadataLinkPreview.feature
  tests/functional/StoreDatasetConnectionsCest.php
Labels: pr:has-ui

#2378 Add new FAQ entries
  CHANGELOG.md
  protected/views/site/faq.php
Labels: pr:simple

#2316 Comment out non-functional API endpoints in help page
  CHANGELOG.md
  protected/views/site/help.php
Labels: pr:simple

#2302 Update FAQ text content
  CHANGELOG.md
  protected/views/site/faq.php
Labels: pr:simple

#2254 Update FAQ. What data storage procedures do you follow?
  CHANGELOG.md
  protected/views/site/faq.php
Labels: pr:simple

#2255 Update FAQ
  CHANGELOG.md
  protected/views/site/faq.php
Labels: pr:simple

#2396 Add db port to secrets template
  CHANGELOG.md
  ops/configuration/variables/secrets-sample
Labels: pr:simple
